name: Deploy to Firebase Hosting on PR
'on': pull_request
jobs:
  build_and_preview:
    if: '${{ github.event.pull_request.head.repo.full_name == github.repository }}'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: create .env file
        run: |
          touch .env.production
          echo VITE_CLIENT_ID=${{ secrets.VITE_CLIENT_ID }} >> .env.production
          echo VITE_CLIENT_SECRET=${{ secrets.VITE_CLIENT_SECRET }} >> .env.production
          echo VITE_OAUTH_TOKEN_URL=${{ secrets.VITE_OAUTH_TOKEN_URL }} >> .env.production
          echo VITE_API_URL=${{ secrets.VITE_API_URL }} >> .env.production
          echo VITE_ANALYTICS_ID=${{ secrets.VITE_ANALYTICS_ID }} >> .env.production
          echo VITE_FIREBASE_API_KEY=${{ secrets.VITE_FIREBASE_API_KEY }} >> .env.production
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '19'
      - name: Install Dependencies
        run: npm i --force
      - name: Build App
        run: npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_PORTFOLIO_SVELTE_2198 }}'
          projectId: portfolio-svelte-2198
