name: Deploy to Firebase Hosting on merge
'on':
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: create .env file
        run: |
          touch .env
          echo CLIENT_ID=${{ secrets.CLIENT_ID }} >> .env
          echo CLIENT_SECRET=${{ secrets.CLIENT_SECRET }} >> .env
          echo OAUTH_TOKEN_URL=${{ secrets.OAUTH_TOKEN_URL }} >> .env
          echo API_URL=${{ secrets.API_URL }} >> .env
          echo ANALYTICS_ID=${{ secrets.ANALYTICS_ID }} >> .env
          echo FIREBASE_API_KEY=${{ secrets.FIREBASE_API_KEY }} >> .env
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '19'
      - name: Install Dependencies
        run: npm i
      - name: Build App
        run: npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_PORTFOLIO_SVELTE_2198 }}'
          channelId: live
          projectId: portfolio-svelte-2198
